from __future__ import annotations
from typing import (
    Any,
    Dict,
    List,
)


class IPDB:
    def __enter__(self) -> IPDB: ...
    def __exit__(self, *args: Any) -> None: ...

    interfaces: Dict[str, Any]

    def create(self, kind: str, **kwargs: Any) -> Any: ...


class IPRoute:
    def __enter__(self) -> IPRoute: ...
    def __exit__(self, *args: Any) -> None: ...

    def link_lookup(self, ifname: str) -> List[Any]: ...
    def get_addr(self, label: str) -> List[Any]: ...
    def get_links(self) -> List[Any]: ...
